# Generated by Django 5.2.13 on 2026-04-17 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(default='인물', max_length=32)),
                ('is_finished', models.BooleanField(default=False)),
                ('final_guess', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.CharField(choices=[('예', '예'), ('아니오', '아니오'), ('잘 모름', '잘 모름')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qas', to='game.gamesession')),
            ],
            options={
                'ordering': ['turn'],
                'constraints': [models.UniqueConstraint(fields=('session', 'turn'), name='unique_session_turn')],
            },
        ),
    ]
