# Generated by Django 5.2.13 on 2026-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='pending_question',
            field=models.TextField(blank=True, default=''),
        ),
    ]
