# Generated by Django 5.2.13 on 2026-04-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamesession_pending_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='candidates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='qa',
            name='question_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
